---
version: 3

tasks:
  gen-proto:
    desc: "Generate the protobuf code"
    cmds:
      - protoc --go_out=pb --go_opt=paths=source_relative
        --go-grpc_out=pb --go-grpc_opt=paths=source_relative
        --proto_path=protobuf protobuf/*.proto
